package com.jacoboaks.wandermobile.game.gameitem;

import android.view.MotionEvent;

import com.jacoboaks.wandermobile.graphics.Font;
import com.jacoboaks.wandermobile.graphics.Material;
import com.jacoboaks.wandermobile.graphics.Model;
import com.jacoboaks.wandermobile.graphics.ShaderProgram;
import com.jacoboaks.wandermobile.graphics.Texture;
import com.jacoboaks.wandermobile.graphics.Transformation;
import com.jacoboaks.wandermobile.util.Bounds;
import com.jacoboaks.wandermobile.util.Color;
import com.jacoboaks.wandermobile.util.Coord;

/**
 * Represents a pressable TextItem.
 */
public class ButtonTextItem extends TextItem {

    //Data
    protected int actionCode;
    protected Color unselectedColor, selectedColor;
    protected boolean selected = false;

    /**
     * Constructs this ButtonTextItem with the given information.
     * @param font the font_default to use for the text
     * @param text the text to display
     * @param unselected the color to use when the button is not texture_selected
     * @param selected the color to use when the button is texture_selected
     * @param actionCode the action code to return when this button is pressed
     */
    public ButtonTextItem(Font font, String text, Color unselected, Color selected, int actionCode) {
        super(font, text, new Material(font.getFontSheet(), unselected, true), 0f, 0f);
        this.unselectedColor = unselected;
        this.selectedColor = selected;
        this.actionCode = actionCode;
    }

    /**
     * Will update this ButtonTextIem based on the user's input.
     * @param e the MotionEvent generated by the user's actions
     * @return this ButtonTextItem's action code if the user has pressed this ButtonTextItem, and
     * -1 otherwise
     */
    public int updateSelection(MotionEvent e) {

        //see if finger is over this button
        Coord touchPos = new Coord(e.getX(), e.getY());
        Transformation.screenToNormalized(touchPos);
        Transformation.normalizedToAspected(touchPos);
        Bounds bounds = this.getBounds();
        boolean fingerOver = bounds.intersects(touchPos);

        //set to appropriate color
        if (fingerOver) {
            if (e.getAction() == MotionEvent.ACTION_UP) { //check if they released on this finger
                this.selected = false;
                this.model.getMaterial().setColor(this.unselectedColor);
                return this.actionCode;
            } else if (!this.selected) { //otherwise make sure appropriate color is texture_selected
                this.model.getMaterial().setColor(this.selectedColor);
                this.selected = true;
            }
        } else {
            if (this.selected) {
                this.model.getMaterial().setColor(this.unselectedColor);
                this.selected = false;
            }
        }

        //return -1 if the user did not press the button
        return -1;
    }

    /**
     * Constructs this ButtonTextItem by copying another ButtonTextItem.
     * @param other the ButtonTextItem to copy from
     */
    public ButtonTextItem(ButtonTextItem other) {
        super(other);
        this.actionCode = other.actionCode;
        this.unselectedColor = other.unselectedColor;
        this.selectedColor = other.selectedColor;
        this.selected = other.selected;
    }

    /**
     * Renders this ButtonTextItem.
     * @param shaderProgram the ShaderProgram to render this ButtonTextItem with
     */
    @Override
    public void render(ShaderProgram shaderProgram) {
        super.render(shaderProgram);
    }

    /**
     * Scales this ButtonTextItem by the given factor.
     * @param factor the factor to scale the model by
     */
    @Override
    public void scale(float factor) {
        super.scale(factor);
    }
}
